// <auto-generated />
using System;
using IntegratedCacheUtils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntegratedCacheUtils.Migrations
{
    [DbContext(typeof(IntegratedTokenCacheDbContext))]
    [Migration("20200722195643_IntegratedTokenCache")]
    partial class IntegratedTokenCache
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IntegratedCacheUtils.Entities.MsalAccountActivity", b =>
                {
                    b.Property<string>("AccountIdentifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountTenantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FailedToAcquireToken")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountIdentifier");

                    b.ToTable("MsalAccountActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
