name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build 1-1-WebApp-BgWorker
      run: dotnet build --configuration Release .\1-Integrated-Cache\1-1-WebApp-BgWorker\IntegratedCache.sln
    - name: Build 1-2-WebApi-BgWorker
      run: dotnet build --configuration Release .\1-Integrated-Cache\1-2-WebApi-BgWorker\IntegratedCache.sln
